New Sources in Search Engine
Magmastream-NPM/magmastream pull request #244
Opened 2024-07-20 18:36 UTC by ItzRandom23

Added New Sources in Search Engine

2024-07-20 19:23 UTC, SxMAbel requested changes

2024-07-20 19:23 UTC, SxMAbel commented on src/structures/Manager.ts
Add your new properties to type 'SearchPlatform'

2024-07-31 02:05 UTC, SxMAbel commented on src/structures/Manager.ts
@ItzRandom23 https://github.com/Blackfort-Hosting/magmastream/pull/244#discussion_r1685522237

2024-08-02 18:35 UTC, ItzRandom23 commented on src/structures/Manager.ts
can you merge it now ?

2024-08-03 13:59 UTC, SxMAbel approved these changes

2024-08-03 17:55 UTC, merged